#!/bin/sh

#---Configuration---#

bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width 1
bspc config window_gap 20
bspc config split_ratio 0.50

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

#---Window---#

bspc rule -r *:*

bspc rule -a Alacritty state=floating
bspc rule -a firefox-bin desktop='^1' follow=on focus=on
bspc rule -a steam desktop='^2'

#---Autostart---#

# Keybinding
sxhkd &

# Notification
dunst &

# Cursor fix
xsetroot -cursor_name left_ptr &

# Wallpaper
sh $HOME/.fehbg &

